---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-14.04
  driver:
    box: ubuntu-14.04
    customize:
      memory: 512
      cpus: 1
    network:
      - [ "private_network", { ip: "192.168.50.5" } ]
- name: ubuntu-12.04
  driver:
    box: ubuntu-12.04
    customize:
      memory: 512
      cpus: 1
    network:
      - [ "private_network", { ip: "192.168.50.5" } ]
- name: debian-6.0.8
  driver:
    box: debian-6.0.8
    customize:
      memory: 512
      cpus: 1
    network:
      - [ "private_network", { ip: "192.168.50.5" } ]
- name: debian-7.2.0
  driver:
    box: debian-7.2.0
    customize:
      memory: 512
      cpus: 1
    network:
      - [ "private_network", { ip: "192.168.50.5" } ]
- name: centos-6.5
  driver:
    box: centos-6.5
    customize:
      memory: 512
      cpus: 1
    network:
      - [ "private_network", { ip: "192.168.50.5" } ]

suites:
  - name: default
    run_list:
    - recipe[icinga-ng]
    attributes:
